import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Button, Navbar, Mark, Card, Person, Attorneys } from "../components";
import { AiFillFileText, AiOutlineVerified, AiOutlineUp } from "react-icons/ai";
import { BsPeopleFill, BsSpeedometer2 } from "react-icons/bs";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from "react-responsive-carousel";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* welcome */}
      <div className="relative w-full overflow-x-hidden  ">
        <Image
          src="/images/cover.png"
          layout="fixed"
          width={2100}
          height={1000}
          alt="cover image"
          className="object-cover "
        />
        <div className="absolute h-full w-full top-0 left-0 bg-black bg-opacity-50 pt-20 px-10 pb-10 text-center md:pt-56">
          <h1 className="font-martel text-white font-bold text-4xl tracking-wide md:pb-10">
            LEGAL PRO SERVICES
          </h1>
          <p className="font-montserrat font-medium text-white text-xl pb-5 md:pb-10">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
            dicta!
          </p>
          <div className="flex flex-col md:flex-row md:justify-center md:gap-3 md:pb-5">
            <Button text="Get Quote Now" outlined={false} colored={true} />
            <Button text="Learn more" outlined={true} colored={false} />
          </div>
          <div className="flex flex-col gap-8 lg:flex-row justify-center lg:gap-0 lg:drop-shadow-2xl ">
            <div className="flex flex-col gap-8 md:flex-row lg:gap-0">
              <Mark
                Icon={AiFillFileText}
                title="1700+"
                description="trusted clients"
              />
              <Mark
                Icon={AiFillFileText}
                title="$180 M"
                description="recovered"
              />
            </div>
            <div className="flex flex-col gap-8 md:flex-row lg:gap-0">
              <Mark
                Icon={AiOutlineVerified}
                title="98%"
                description="successful cases"
              />
              <Mark
                Icon={AiOutlineUp}
                title="10,6"
                description="injury cases"
              />
            </div>
          </div>
        </div>
      </div>
      {/* what we do  & who we are*/}
      <div className="bg-neutral-100 pb-36">
        <div className=" py-8 flex flex-col gap-8 lg:flex-row justify-center lg:gap-0 lg:mx-52 ">
          <div className="flex flex-col gap-8 md:flex-row lg:gap-0">
            <Card
              Icon={AiFillFileText}
              Title="Frauds or Misleads"
              Description="
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab, vel.
      "
              Colored={false}
              ButtonText="More"
            />{" "}
            <Card
              Icon={AiOutlineVerified}
              Title="Bailes & Warrants"
              Description="
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab, vel.
      "
              Colored={false}
              ButtonText="More"
            />{" "}
          </div>
          <div className="flex flex-col gap-8 md:flex-row lg:gap-0">
            <Card
              Icon={AiFillFileText}
              Title="Federal Drug Crimes"
              Description="
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab, vel.
      "
              Colored={false}
              ButtonText="More"
            />{" "}
            <Card
              Icon={AiFillFileText}
              Title="Traffic Related Crimes"
              Description="
      Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ab, vel.
      "
              Colored={true}
              ButtonText="More"
            />{" "}
          </div>
        </div>
        <div className="flex flex-col text-center justify-center mt-8 ">
          <h2 className="font-martel font-bold text-4xl tracking-wide">
            Who We Are
          </h2>
          <p
            className="font-opensans text-sm tracking-wide mx-20
           lg:mx-96 mb-8"
          >
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum,
            sapiente quisquam.
          </p>
          <div className="flex flex-col lg:flex-row justify-between xl:mx-44">
            <div className="block w-full h-auto px-9 mb-12  ">
              <Image
                src="/images/video.png"
                layout="responsive"
                width="594"
                height="442"
                alt=""
              />
            </div>
            <div className="flex flex-col  text-left px-9  ">
              <h3 className="font-martel font-bold text-4xl ">
                Most trusted in our field
              </h3>
              <p className="mb-10">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio
                rem facilis vel quidem libero esse?
              </p>
              <div className="flex flex-row mb-7">
                <BsPeopleFill className="text-yellow-500 w-8 h-8 mr-5 " />
                <div>
                  <p className="font-martel font-bold text-base">
                    Lorem ipsum, dolor sit amet consectetur adipisicing.
                  </p>
                  <p className="font-opensans font-bold text-base text-slate-700">
                    Lorem, ipsum dolor.
                  </p>
                </div>
              </div>
              <div className="flex flex-row">
                <BsSpeedometer2 className="text-yellow-500 w-8 h-8 mr-5" />
                <div>
                  <p className="font-martel font-bold text-base">
                    Lorem ipsum, dolor sit amet consectetur adipisicing.
                  </p>
                  <p className="font-opensans font-bold text-base text-slate-700">
                    Lorem, ipsum dolor.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* what clients say */}
      <div className="bg-blue-600 px-5 lg:px-10 pb-10">
        <h2 className="font-martel font-bold text-4xl text-white mx-14 pt-16 mb-4 text-center">
          What Clients Say
        </h2>
        <p className="font-opensans text-sm text-white mx-14 text-center pb-10 ">
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Autem nisi
          iusto, optio pariatur impedit inventore.
        </p>
        <Carousel
          infiniteLoop
          showStatus={false}
          showArrows={true}
          showIndicators={false}
        >
          <Person
            Name="Regina Miles"
            Role="Designer"
            Rating={4}
            Description="
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil nam numquam nobis quo, sequi quos error inventore sint obcaecati voluptatibus.
        
        "
            ImageLink="/images/Avatar.png"
          />
          <Person
            Name="Regina Miles"
            Role="Designer"
            Rating={4}
            Description="
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil nam numquam nobis quo, sequi quos error inventore sint obcaecati voluptatibus.
        
        "
            ImageLink="/images/Avatar.png"
          />
          <Person
            Name="Regina Miles"
            Role="Designer"
            Rating={4}
            Description="
    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nihil nam numquam nobis quo, sequi quos error inventore sint obcaecati voluptatibus.
        
        "
            ImageLink="/images/Avatar.png"
          />
        </Carousel>
      </div>
      {/* meet our attorneys */}
      <div className="bg-neutral-100 px-8 py-20 text-center lg:px-16">
        <h2 className="font-martel font-bold text-4xl mb-3">
          Meet Our Attorneys
        </h2>
        <p className="font-opensans text-sm mb-10 ">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae
          consequatur ut, voluptate repudiandae cum eveniet id temporibus.
          Dolore, amet numquam.
        </p>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Attorneys
            ImageLink="/images/Avatar.png"
            Name="Ashley Fletcher"
            Description="
    Lorem ipsum dolor sit amet.
    "
            Role="LAYER & CEO"
          />{" "}
          <Attorneys
            ImageLink="/images/Avatar.png"
            Name="Ashley Fletcher"
            Description="
    Lorem ipsum dolor sit amet.
    "
            Role="LAYER & CEO"
          />
          <Attorneys
            ImageLink="/images/Avatar.png"
            Name="Ashley Fletcher"
            Description="
    Lorem ipsum dolor sit amet.
    "
            Role="LAYER & CEO"
          />
          <Attorneys
            ImageLink="/images/Avatar.png"
            Name="Ashley Fletcher"
            Description="
    Lorem ipsum dolor sit amet.
    "
            Role="LAYER & CEO"
          />
        </div>
      </div>
      {/* branches all over world */}
      <div className="bg-blue-900 flex flex-col px-10 py-20 md:py-10 lg:py-20 md:flex-row ">
        <div className="flex flex-col">
          <h2 className="font-martel font-bold text-4xl text-white mb-4">
            We Have Branches All Over The World
          </h2>
          <p className="font-opensans text-white mb-24 ">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nisi, illo
            explicabo culpa molestias ipsum exercitationem aspernatur dolor
            consequatur repellat accusamus.
          </p>
        </div>
        <div className="flex md:px-16 ">
          <div className="block w-80 h-32 my-auto ">
            <Image
              src="/images/world.png"
              layout="responsive"
              width={313}
              height={169}
              alt="World image"
            />
          </div>
        </div>
      </div>
      {/* request consultation */}
      <div className="grid grid-cols-12 lg:mx-40">
        <div className=" block col-span-12 lg:col-span-3 mb-10 ">
          <Image
            src="/images/cover2.png"
            layout="responsive"
            width={364}
            height={637}
            alt="Cover"
            className=""
          />
        </div>
        <div className="col-span-12 lg:col-span-9 mx-10 lg:p-10">
          <h2 className="font-martel font-bold text-3xl text-left mb-10">
            Request A Free Consultation
          </h2>
          <div>
            <p className="font-bold mb-2">Name*</p>
            <input
              type="text"
              placeholder="Full Name"
              className=" py-3 px-5 border-zinc-800 border rounded-md mb-3 w-full bg-zinc-100"
            />
            <p className="font-bold mb-2">Email*</p>
            <input
              type="text"
              placeholder="example@gmail.com"
              className=" py-3 px-5 border-zinc-800 border rounded-md mb-3 w-full bg-zinc-100"
            />
            <p className="font-bold mb-2">Department*</p>
            <input
              type="text"
              placeholder="N1S Street 12"
              className=" py-3 px-5 border-zinc-800 border rounded-md mb-3 w-full bg-zinc-100"
            />{" "}
            <p className="font-bold mb-2">Time*</p>
            <input
              type="text"
              placeholder="4:00"
              className=" py-3 px-5 border-zinc-800 border rounded-md mb-3 w-full bg-zinc-100"
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
